### ISSUE TITLE
Repository description

### ISSUE THREAD

**Issue by zachlatta** [hackclub/imgur-uploader-surrogate#2]
As mentioned in #1, I'm not super sure what this repository is. Any chance a repository description could be added on GitHub so I (and others) could easily see what this repository is?

**Comment by zachlatta** [comment]
Since we're no longer using this repository, let's go ahead and deprecate it.

To deprecate it:

- Add a `[DEPRECATED]` prefix to the repository description
- Create a README saying that this repository is deprecated and no longer maintained
- Close all existing issues

**Comment by jkwok91** [comment]
Closing because the repo is being deprecated (https://github.com/hackclub/imgur-uploader-surrogate/issues/2)
